ia-frontend-install:
	cd apps/instagram-analyzer/frontend && npm install

ia-frontend-dev:
	cd apps/instagram-analyzer/frontend && npm run dev

ia-frontend-build:
	cd apps/instagram-analyzer/frontend && npm run build

ia-frontend-lint:
	cd apps/instagram-analyzer/frontend && npm run lint
