ll-frontend-install:
	cd apps/language-learning/frontend && npm install

ll-frontend-dev:
	cd apps/language-learning/frontend && npm run dev

ll-frontend-build:
	cd apps/language-learning/frontend && npm run build

ll-frontend-lint:
	cd apps/language-learning/frontend && npm run lint
