ll-docker-build-backend:
	docker build -f packaging/language-learning/backend/Dockerfile -t ll-backend .

ll-docker-build-frontend:
	docker build -f packaging/language-learning/frontend/Dockerfile -t ll-frontend .

ll-docker-build: ll-docker-build-backend ll-docker-build-frontend
