pf-frontend-install:
	cd apps/personal-finance/frontend && npm install

pf-frontend-dev:
	cd apps/personal-finance/frontend && npm run dev

pf-frontend-build:
	cd apps/personal-finance/frontend && npm run build

pf-frontend-lint:
	cd apps/personal-finance/frontend && npm run lint
